/* ============================================================
   PaisaOffers - static JSON deals renderer
   Source: data/deals.json generated by tools/publish_deals.py
   ============================================================ */

const DEALS_URL = "/data/deals.json";
const PAGE_SIZE = 12;

let allDeals = [];
let hotDeals = [];
let filteredDeals = [];
let visibleCount = PAGE_SIZE;

function fmt(num) {
  return Number(num || 0).toLocaleString("en-IN");
}

function safeStr(val) {
  if (val === null || val === undefined) return "";
  return String(val).trim();
}

function escHtml(str) {
  return safeStr(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escAttr(str) {
  return escHtml(str);
}

function normalizeDeal(deal) {
  return {
    asin: safeStr(deal.asin),
    title: safeStr(deal.title) || "Deal",
    image_url: safeStr(deal.image_url),
    deal_price: Number(deal.deal_price || 0),
    original_price: Number(deal.original_price || 0),
    discount_percent: Number(deal.discount_percent || 0),
    category: safeStr(deal.category),
    affiliate_link: safeStr(deal.affiliate_link) || "#",
    description: safeStr(deal.description),
    date_added: safeStr(deal.date_added),
    expiry_date: safeStr(deal.expiry_date),
    tags: Array.isArray(deal.tags) ? deal.tags.map(safeStr).filter(Boolean) : [],
    is_hot_deal: Boolean(deal.is_hot_deal)
  };
}

async function fetchDealsJson() {
  if (window.location.protocol === "file:") {
    return { generated_at: "", total_deals: 0, hot_deals: [], all_deals: [] };
  }

  const primaryUrl = DEALS_URL + "?t=" + Date.now();
  const res = await fetch(primaryUrl);
  if (!res.ok) throw new Error("HTTP " + res.status);
  return await res.json();
}

async function loadDeals() {
  try {
    const payload = await fetchDealsJson();
    const dataDeals = Array.isArray(payload.all_deals) ? payload.all_deals : [];
    const dataHotDeals = Array.isArray(payload.hot_deals) ? payload.hot_deals : [];

    allDeals = dataDeals.map(normalizeDeal);
    hotDeals = dataHotDeals.map(normalizeDeal);

    if (hotDeals.length === 0) {
      hotDeals = allDeals
        .filter(deal => deal.is_hot_deal)
        .sort(sortByDiscount)
        .slice(0, 6);
    }

    applyFilters();
    renderHotDeals();
  } catch (err) {
    console.error("[PaisaOffers] Failed to load deals:", err);
    showErrorState();
  }
}

function renderHotDeals() {
  const container = document.getElementById("hotGrid");
  if (!container) return;

  const deals = hotDeals.slice(0, 6);
  if (deals.length === 0) {
    container.innerHTML = emptyState("No hot deals right now. Check back soon.");
    return;
  }

  container.innerHTML = deals.map(card).join("");
}

function renderDeals() {
  const grid = document.getElementById("dealsGrid");
  if (!grid) return;

  const slice = filteredDeals.slice(0, visibleCount);
  if (slice.length === 0) {
    grid.innerHTML = emptyState("No deals found. Try another search.");
    setLoadMoreVisible(false);
    return;
  }

  grid.innerHTML = slice.map(card).join("");
  setLoadMoreVisible(filteredDeals.length > visibleCount);
}

function emptyState(message) {
  return `<div class="empty-state">${escHtml(message)}</div>`;
}

function showErrorState() {
  const message = "Deals could not be loaded. Please try again shortly.";
  const hotGrid = document.getElementById("hotGrid");
  const dealsGrid = document.getElementById("dealsGrid");
  if (hotGrid) hotGrid.innerHTML = emptyState(message);
  if (dealsGrid) dealsGrid.innerHTML = emptyState(message);
  setLoadMoreVisible(false);
  updateCount();
}

function setLoadMoreVisible(show) {
  const wrap = document.getElementById("loadMoreWrap");
  if (wrap) wrap.style.display = show ? "block" : "none";
}

function card(deal) {
  const imgSrc = deal.image_url || "https://via.placeholder.com/300x300?text=No+Image";
  const badge = deal.discount_percent > 0
    ? `<span class="discount-badge">${deal.discount_percent}% OFF</span>`
    : "";
  const category = deal.category
    ? `<span class="category-badge">${escHtml(deal.category)}</span>`
    : "";
  const description = deal.description
    ? `<div class="deal-hook">${escHtml(deal.description)}</div>`
    : "";
  const oldPrice = deal.original_price > 0
    ? `<span class="old-price">Rs. ${fmt(deal.original_price)}</span>`
    : "";
  const whatsappText = encodeURIComponent(
    "Hot deal: " + deal.title +
    "\n\nPrice: Rs. " + fmt(deal.deal_price) +
    (deal.original_price ? " (MRP Rs. " + fmt(deal.original_price) + ")" : "") +
    "\n\nBuy Now: " + deal.affiliate_link
  );
  const whatsappLink = "https://wa.me/?text=" + whatsappText;

  return `<div class="deal-card">
  <div class="deal-img-wrap">
    <img src="${escAttr(imgSrc)}" alt="${escAttr(deal.title)}" loading="lazy"
         onerror="this.src='https://via.placeholder.com/300x300?text=No+Image'">
    ${badge}
    ${category}
  </div>
  <div class="deal-body">
    <div class="deal-title">${escHtml(deal.title)}</div>
    ${description}
    <div class="deal-prices">
      <span class="new-price">Rs. ${fmt(deal.deal_price)}</span>
      ${oldPrice}
    </div>
    <div class="deal-actions">
      <a href="${escAttr(deal.affiliate_link)}" target="_blank" rel="nofollow sponsored noopener" class="btn-buy"
         onclick="trackClick('${escAttr(deal.asin)}', '${escAttr(deal.title)}')"><i class="fas fa-shopping-cart"></i> Buy</a>
      <a href="${escAttr(whatsappLink)}" target="_blank" rel="noopener" class="btn-wa" aria-label="Share on WhatsApp"><i class="fab fa-whatsapp"></i></a>
    </div>
  </div>
</div>`;
}

function loadMore() {
  visibleCount += PAGE_SIZE;
  renderDeals();
}

function updateCount() {
  const el = document.getElementById("dealCount");
  if (el) el.innerText = filteredDeals.length + " deals";
}

function handleSearch() {
  applyFilters();
}

function applyFilters() {
  const searchEl = document.getElementById("searchInput");
  const query = safeStr(searchEl ? searchEl.value : "").toLowerCase();

  filteredDeals = query
    ? allDeals.filter(deal => searchableText(deal).includes(query))
    : [...allDeals];

  const sortEl = document.getElementById("filterSort");
  const sortValue = sortEl ? sortEl.value : "discount";
  filteredDeals.sort(sortValue === "latest" ? sortByLatest : sortByDiscount);

  visibleCount = PAGE_SIZE;
  renderDeals();
  updateCount();
}

function searchableText(deal) {
  return [
    deal.title,
    deal.category,
    deal.tags.join(" ")
  ].join(" ").toLowerCase();
}

function sortByDiscount(a, b) {
  return (b.discount_percent || 0) - (a.discount_percent || 0);
}

function sortByLatest(a, b) {
  return new Date(b.date_added || 0) - new Date(a.date_added || 0);
}

function trackClick(asin, title) {
  if (typeof window.gtag === "function") {
    window.gtag("event", "affiliate_click", {
      event_category: "affiliate",
      event_label: title,
      asin: asin
    });
  }
}

window.loadMore = loadMore;
window.handleSearch = handleSearch;
window.applyFilters = applyFilters;
window.trackClick = trackClick;

document.addEventListener("DOMContentLoaded", loadDeals);
